baseURL: "https://complex2math.com"
languageCode: "en-us"
title: "Homepage of Complex2-Liu"
hasCJKLanguage: true

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: blog
    name: Blog
    url: /blog
    weight: 2
  - identifier: blog-template
    name: Template
    url: /blog/template
    parent: blog
    weight: 1
  - identifier: problems
    name: Problems
    url: /problems
    weight: 3
  - identifier: bookcase
    name: Bookcase
    url: /bookcase
    weight: 4

params:
  since: 2021
